testname: webMUSHRA Example
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to VIOLIN-VALLE Test!       
    - type: mushra
      id: trial1
      name: MUSHRA
      content: VIOLIN-VALLE test training page.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/prompt_legato.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/prompt_legato.wav
          C2: configs/resources/audio/prompt_pizz.wav
          C3: configs/resources/audio/prompt_harmonic.wav
    - 
          - random
          - type: mushra
            id: trial_random_1
            name: MUSHRA - Random 2
            content: Test X
            enableLooping: true 
            reference: configs/resources/audio/prompt_harmonic.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/prompt_harmonic.wav
                C2: configs/resources/audio/prompt_pizz.wav
                C3: configs/resources/audio/prompt_legato.wav
          - type: mushra
            id: trial_random_2
            name: MUSHRA - Random 1
            content: Test Y
            enableLooping: true 
            reference: configs/resources/audio/prompt_pizz.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/prompt_pizz.wav
                C2: configs/resources/audio/prompt_harmonic.wav
                C3: configs/resources/audio/prompt_legato.wav
    - type: finish
      name: Thank you
      content: Thank you for attending our test!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          # - type: number
          #   label: Age
          #   name: age
          #   min: 0
          #   max: 100
          #   default: 30
          # - type: likert
          #   name: gender
          #   label: Gender
          #   response:
          #    - value: female
          #      label: Female
          #    - value: male
          #      label: Male
          #    - value: other
          #      label: Other
